export const Experience = [
    {"type":"workExperience", "name":"City of Maple Grove", "title":"Utilities Department Worker", "Description":"Responsible for service and maintenance of 20 fire hydrants, 300 emergency water shut off valves, and 250 manhole covers", "date":"May 20, 2024 - August 16, 2024"},
    {"type":"workExperience", "name":"Iowa State University", "title":"Lab Assistant", "Description":"Responsible for service, repair, and maintenance of 2 aged to ensure optimal functionality and measurement. Researched and identified 4 repair parts to order from system vendor. Set up 2 vendor meetings to address system requirements and obtain quotes for new systems for lab manager.", "date":"September 26, 2023 - February 1, 2024"},
    {"type":"workExperience", "name":"Menards", "title":"Sales Representative – Electrical & Lighting", "Description":"Responsible for customer support in identifying and finding items in the department, stocking shelves, and light installation.", "date":"July 2020 - July 2023"},
    {"type":"cert", "name":"Tripoli Level 2 High Powered Rocketry #24629", "Description":"The Tripoli Level 2 High Powered Rocketry Certification allows individuals to design, build, and successfully launch a high-powered rocket with a motor exceeding 2,500 feet per second. Certification requires the completion of a successful flight, along with detailed documentation. Upon passing, certified individuals can legally purchase and launch high-power motors and participate in advanced rocketry projects. Level 2 certification demonstrates proficiency in rocket design, flight stability, recovery systems, and safety, opening doors to more complex rocketry activities.","date":"May 2023"},
    {"type":"club", "name":"Cyclone Rocketry Club", "title":"Mechanical Sub-Team Member", "Description":"Lead the design and fabrication of a piston ejection system with a focus on developing an airtight burst disk system. Machined 9 total components of the piston ejection system assembly using CNC mills and lathes. Conducted 12 hydrostatic tests of the piston ejection system parts to validate burst disk failure pressure and safe operation.", "date":"August 2022 - Present"},
    {"type":"club", "name":"Cyclone Rocketry Club", "title":"Honeywell FM&T Rocketry Student Launch Contract Team Member", "Description":"Performed FEA analysis on flight components and used ASNI standards to tolerance 3 avionics bulkheads. Responsible for design of avionics housing and coupler with focus on ease of removal and manufacturing. Presented avionics housing and coupler designs to Honeywell FM&T sponsor for approval.", "date":"August 2024 - Present"},
    {"type":"club", "name":"Cyclone Rocketry Club", "title":"HPR Chair Lead", "Description":"Planned, gained approval, and managed a $4,000 club budget. Responsible for managing club rocket kits and distributing them to 15 club members. Taught 15 club members the design, construction, and simulation of high-powered rocketry in SolidWorks and OpenRocket. Provided guidance through the level 1 and level 2 certification processes for 15 members.", "date":"July 2023 - June 2024"},

];
